version: '3.8'

services:
  face_recognition:
    image: python:3.9
    container_name: face_recognition_app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    command: ["python", "script.py"]
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - cmake
    build:
      context: .
      dockerfile: Dockerfile

  cmake:
    image: ubuntu:latest
    container_name: cmake_installer
    restart: unless-stopped
    command: >
      sh -c "apt-get update && apt-get install -y cmake && cmake --version"